# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]

# permissions:
#   contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
       # 设置服务器时区为东八区 
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - uses: actions/checkout@v3
#       with:
#         persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
#         fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        git clone https://github.com/LinghaoChan/CSSummerCamp2022.git
        git clone https://github.com/CS-BAOYAN/CSYuTuiMian2022.git
        python ./run.py
        cat ./README.md
        mkdir abab
        mkdir ./abab/.github
        mkdir ./abab/.github/workflows
        mv ./README.md ./abab/README.md
        mv ./XOR.md ./abab/XOR.md
        mv ./.github/workflows/python-app.yml ./abab/.github/workflows/python-app.yml
        mv ./run.py ./abab/run.py
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: main
        FOLDER: abab
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
